---
- name: Install the Resource manager packages
  apt: name={{ item }} state=installed
  with_items: 
    - hadoop-yarn-resourcemanager
    - hadoop-mapreduce-historyserver
    - hadoop-yarn-proxyserver
  tags:
    - install

- include_vars: roles/hadoop_common/vars/main.yml
  tags:
    - configure

- name: Copy the hadoop configuration files
  template: src=roles/hadoop_common/templates/conf/{{ item }}.j2 dest=/etc/hadoop/conf/{{ item }}
  with_items: 
   - core-site.xml
   - hdfs-site.xml
   - slaves
  notify: restart hadoop master services
  tags:
    - configure

